title: LDPC Codes
email: yairmazal@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This site contains my notes regarding hte theory and implementation of LDPC codes.
domain: yairmz.github.io
baseurl: /LDPC # the subpath of your site, e.g. /blog
url: https://yairmz.github.io # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  YairMZ

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Supports true (default) or false
search_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "See on GitHub":
    - "https://github.com/YairMZ/LDPC"

# footer
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/YairMZ/LDPC" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# bibliography
bib_sources:
  - {id: "ryan",
     name: "An Introduction to LDPC Codes",
     author: "William E. Ryan",
     url: "http://tuk88.free.fr/LDPC/ldpcchap.pdf"}