title: LDPC Codes
email: yairmazal@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This site contains my notes regarding hte theory and implementation of LDPC codes.
domain: yairmz.github.io
baseurl: /LDPC # the subpath of your site, e.g. /blog
url: https://yairmz.github.io # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  YairMZ

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Supports true (default) or false
search_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "See on GitHub":
    - "https://github.com/YairMZ/LDPC"